import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/NavBar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          antialiased
        `}
      >
        <NavBar />
        <main
          className={`
            flex min-h-screen flex-col bg-gray-300 pr-6 pl-6
            lg:pl-72
          `}
        >
          {children}
        </main>
        <footer className={`bg-gray-100 p-4 text-center`}>
          <p className="text-gray-600">© 2023 My Personal Web. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
