const getEnv = (value: string | undefined, fallback: string = ''): string => {
  return value ?? fallback;
};

const EMAILJS_SERVICE_ID = getEnv(process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID);
const EMAILJS_TEMPLATE_ID = getEnv(process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID);
const EMAILJS_PUBLIC_KEY = getEnv(process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY);
const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || 'https://hdygidev.netlify.app').replace(
  /\/$/,
  ''
);

const GOOGLE_MAP_URL = getEnv(process.env.NEXT_PUBLIC_GOOGLE_MAP_URL);
const FILE_RESUME_URL = getEnv(process.env.NEXT_PUBLIC_FILE_RESUME_URL);

const CERTIFICATE_QSD_URL = getEnv(process.env.NEXT_PUBLIC_CERTIFICATE_QSD_URL);
const CERTIFICATE_ENGLISH_URL = getEnv(process.env.NEXT_PUBLIC_CERTIFICATE_ENGLISH_URL);
const CERTIFICATE_REACT_URL = getEnv(process.env.NEXT_PUBLIC_CERTIFICATE_REACT_URL);

const ACCOUNT_MAIL = getEnv(process.env.NEXT_PUBLIC_ACCOUNT_MAIL);
const ACCOUNT_PHONE = getEnv(process.env.NEXT_PUBLIC_ACCOUNT_PHONE);
const ACCOUNT_GITHUB_URL = getEnv(process.env.NEXT_PUBLIC_ACCOUNT_GITHUB_URL);
const ACCOUNT_LINKEDIN_URL = getEnv(process.env.NEXT_PUBLIC_ACCOUNT_LINKEDIN_URL);
const ACCOUNT_CONTRA_URL = getEnv(process.env.NEXT_PUBLIC_ACCOUNT_CONTRA_URL);
const ACCOUNT_UPWORK_URL = getEnv(process.env.NEXT_PUBLIC_ACCOUNT_UPWORK_URL);
const ACCOUNT_WHATSAPP_URL = getEnv(process.env.NEXT_PUBLIC_ACCOUNT_WHATSAPP_URL);

const PORTFOLIO_WONDERFUL_QURAN_API_IMAGE_URL = getEnv(
  process.env.NEXT_PUBLIC_PORTFOLIO_WONDERFUL_QURAN_API_IMAGE_URL
);
const PORTFOLIO_WONDERFUL_QURAN_API_LIVE_URL = getEnv(
  process.env.NEXT_PUBLIC_PORTFOLIO_WONDERFUL_QURAN_API_LIVE_URL
);
const PORTFOLIO_WONDERFUL_QURAN_API_GITHUB_URL = getEnv(
  process.env.NEXT_PUBLIC_PORTFOLIO_WONDERFUL_QURAN_API_GITHUB_URL
);
const PORTFOLIO_TIME_DEPOSIT_BANK_ACCOUNT_IMAGE_URL = getEnv(
  process.env.NEXT_PUBLIC_PORTFOLIO_TIME_DEPOSIT_BANK_ACCOUNT_IMAGE_URL
);
const PORTFOLIO_TIME_DEPOSIT_BANK_ACCOUNT_LIVE_URL = getEnv(
  process.env.NEXT_PUBLIC_PORTFOLIO_TIME_DEPOSIT_BANK_ACCOUNT_LIVE_URL
);
const PORTFOLIO_P2P_EDUCATION_MODULE_IMAGE_URL = getEnv(
  process.env.NEXT_PUBLIC_PORTFOLIO_P2P_EDUCATION_MODULE_IMAGE_URL
);
const PORTFOLIO_P2P_EDUCATION_MODULE_LIVE_URL = getEnv(
  process.env.NEXT_PUBLIC_PORTFOLIO_P2P_EDUCATION_MODULE_LIVE_URL
);
const PORTFOLIO_SFMONITOR_AGENT_CONNECTOR_AMQ_IMAGE_URL = getEnv(
  process.env.NEXT_PUBLIC_PORTFOLIO_SFMONITOR_AGENT_CONNECTOR_AMQ_IMAGE_URL
);
const PORTFOLIO_WONDERFUL_QURAN_WEB_IMAGE_URL = getEnv(
  process.env.NEXT_PUBLIC_PORTFOLIO_WONDERFUL_QURAN_WEB_IMAGE_URL
);
const PORTFOLIO_WONDERFUL_QURAN_WEB_LIVE_URL = getEnv(
  process.env.NEXT_PUBLIC_PORTFOLIO_WONDERFUL_QURAN_WEB_LIVE_URL
);
const PORTFOLIO_WONDERFUL_QURAN_WEB_GITHUB_URL = getEnv(
  process.env.NEXT_PUBLIC_PORTFOLIO_WONDERFUL_QURAN_WEB_GITHUB_URL
);
const PORTFOLIO_MY_PERSONAL_WEB_IMAGE_URL = getEnv(
  process.env.NEXT_PUBLIC_PORTFOLIO_MY_PERSONAL_WEB_IMAGE_URL
);
const PORTFOLIO_MY_PERSONAL_WEB_LIVE_URL = getEnv(
  process.env.NEXT_PUBLIC_PORTFOLIO_MY_PERSONAL_WEB_LIVE_URL
);
const PORTFOLIO_MY_PERSONAL_WEB_GITHUB_URL = getEnv(
  process.env.NEXT_PUBLIC_PORTFOLIO_MY_PERSONAL_WEB_GITHUB_URL
);
const PORTFOLIO_SFMONITOR_DASHBOARD_IMAGE_URL = getEnv(
  process.env.NEXT_PUBLIC_PORTFOLIO_SFMONITOR_DASHBOARD_IMAGE_URL
);
const PORTFOLIO_NAVEES_IMAGE_URL = getEnv(process.env.NEXT_PUBLIC_PORTFOLIO_NAVEES_IMAGE_URL);
const PORTFOLIO_NAVEES_LIVE_URL = getEnv(process.env.NEXT_PUBLIC_PORTFOLIO_NAVEES_LIVE_URL);

export {
  ACCOUNT_CONTRA_URL,
  ACCOUNT_GITHUB_URL,
  ACCOUNT_LINKEDIN_URL,
  ACCOUNT_MAIL,
  ACCOUNT_PHONE,
  ACCOUNT_UPWORK_URL,
  ACCOUNT_WHATSAPP_URL,
  CERTIFICATE_ENGLISH_URL,
  CERTIFICATE_QSD_URL,
  CERTIFICATE_REACT_URL,
  EMAILJS_PUBLIC_KEY,
  EMAILJS_SERVICE_ID,
  EMAILJS_TEMPLATE_ID,
  FILE_RESUME_URL,
  GOOGLE_MAP_URL,
  PORTFOLIO_MY_PERSONAL_WEB_GITHUB_URL,
  PORTFOLIO_MY_PERSONAL_WEB_IMAGE_URL,
  PORTFOLIO_MY_PERSONAL_WEB_LIVE_URL,
  PORTFOLIO_NAVEES_IMAGE_URL,
  PORTFOLIO_NAVEES_LIVE_URL,
  PORTFOLIO_P2P_EDUCATION_MODULE_IMAGE_URL,
  PORTFOLIO_P2P_EDUCATION_MODULE_LIVE_URL,
  PORTFOLIO_SFMONITOR_AGENT_CONNECTOR_AMQ_IMAGE_URL,
  PORTFOLIO_SFMONITOR_DASHBOARD_IMAGE_URL,
  PORTFOLIO_TIME_DEPOSIT_BANK_ACCOUNT_IMAGE_URL,
  PORTFOLIO_TIME_DEPOSIT_BANK_ACCOUNT_LIVE_URL,
  PORTFOLIO_WONDERFUL_QURAN_API_GITHUB_URL,
  PORTFOLIO_WONDERFUL_QURAN_API_IMAGE_URL,
  PORTFOLIO_WONDERFUL_QURAN_API_LIVE_URL,
  PORTFOLIO_WONDERFUL_QURAN_WEB_GITHUB_URL,
  PORTFOLIO_WONDERFUL_QURAN_WEB_IMAGE_URL,
  PORTFOLIO_WONDERFUL_QURAN_WEB_LIVE_URL,
  SITE_URL
};
